Repository Moyuyanli/HuYanEconomy, pull requests merged in 2024-08, with the labels that each got.

#3 修复BUG & 添加功能
  src/main/java/cn/chahuyun/economy/HuYanEconomy.java
  src/main/java/cn/chahuyun/economy/entity/fish/FishInfo.java
  src/main/java/cn/chahuyun/economy/event/MessageEventListener.java
  src/main/java/cn/chahuyun/economy/manager/BankManager.java
  src/main/java/cn/chahuyun/economy/manager/GamesManager.java
  src/main/java/cn/chahuyun/economy/manager/TransferManager.java
  src/main/java/cn/chahuyun/economy/plugin/PluginManager.java
  src/main/java/cn/chahuyun/economy/utils/EconomyUtil.java
  src/main/java/cn/chahuyun/economy/utils/HibernateUtil.java
  src/main/kotlin/cn/chahuyun/config/EconomyConfig.kt
  src/main/kotlin/cn/chahuyun/config/FishingMsgConfig.kt
Labels: bug, enhancement

#4 添加功能
  src/main/java/cn/chahuyun/economy/entity/UserInfo.java
  src/main/java/cn/chahuyun/economy/plugin/PluginManager.java
  src/main/java/cn/chahuyun/economy/version/CheckLatestVersion.java
  src/main/kotlin/cn/chahuyun/economy/config/EconomyConfig.kt
Labels: enhancement

#5 feat：实现红包功能
  src/main/java/cn/chahuyun/economy/entity/redpack/RedPack.java
  src/main/java/cn/chahuyun/economy/event/MessageEventListener.java
  src/main/java/cn/chahuyun/economy/manager/GamesManager.java
  src/main/java/cn/chahuyun/economy/manager/RedPackManager.java
  src/main/java/cn/chahuyun/economy/manager/TitleManager.java
  src/main/java/cn/chahuyun/economy/plugin/PluginManager.java
  src/main/java/cn/chahuyun/economy/utils/TimeConvertUtil.java
  src/main/java/cn/chahuyun/economy/version/CheckLatestVersion.java
Labels: enhancement

#6 [feat]添加红包功能
  README.md
  build.gradle.kts
  src/main/java/cn/chahuyun/economy/HuYanEconomy.java
  src/main/java/cn/chahuyun/economy/constant/Icon.java
  src/main/java/cn/chahuyun/economy/entity/redpack/RedPack.java
  src/main/java/cn/chahuyun/economy/event/MessageEventListener.java
  src/main/java/cn/chahuyun/economy/manager/GamesManager.java
  src/main/java/cn/chahuyun/economy/manager/RedPackManager.java
  src/main/java/cn/chahuyun/economy/manager/TitleManager.java
  src/main/java/cn/chahuyun/economy/utils/TimeConvertUtil.java
Labels: bug, documentation, enhancement

#7 feat: 添加"抢劫"功能
  src/main/java/cn/chahuyun/economy/HuYanEconomy.java
  src/main/java/cn/chahuyun/economy/entity/rob/RobInfo.java
  src/main/java/cn/chahuyun/economy/event/MessageEventListener.java
  src/main/java/cn/chahuyun/economy/manager/RobManager.java
  src/main/java/cn/chahuyun/economy/utils/ShareUtils.java
  src/main/java/cn/chahuyun/economy/utils/TimeConvertUtil.java
  src/main/kotlin/cn/chahuyun/economy/config/RobMsgConfig.kt
Labels: enhancement

#9 [feat] 添加抢劫功能，添加自定义称号功能
  README.md
  build.gradle.kts
  src/main/java/cn/chahuyun/economy/HuYanEconomy.java
  src/main/java/cn/chahuyun/economy/entity/rob/RobInfo.java
  src/main/java/cn/chahuyun/economy/entity/title/CustomTitle.java
  src/main/java/cn/chahuyun/economy/entity/title/TitleTemplateSimpleImpl.java
  src/main/java/cn/chahuyun/economy/event/MessageEventListener.java
  src/main/java/cn/chahuyun/economy/manager/GamesManager.java
  src/main/java/cn/chahuyun/economy/manager/RedPackManager.java
  src/main/java/cn/chahuyun/economy/manager/RobManager.java
  src/main/java/cn/chahuyun/economy/plugin/TitleTemplateManager.java
  src/main/java/cn/chahuyun/economy/utils/ShareUtils.java
  src/main/java/cn/chahuyun/economy/utils/TimeConvertUtil.java
  src/main/kotlin/cn/chahuyun/economy/config/RobMsgConfig.kt
  src/test/java/Test.java
Labels: bug, documentation, enhancement

#11 [fix]修复自定义称号
  build.gradle.kts
  src/main/java/cn/chahuyun/economy/HuYanEconomy.java
  src/main/java/cn/chahuyun/economy/entity/title/CustomTitle.java
  src/main/java/cn/chahuyun/economy/manager/TitleManager.java
  src/main/java/cn/chahuyun/economy/plugin/TitleTemplateManager.java
Labels: bug

#12 [fix] 修复众多bug，优化红包算法，优化一言异步管理
  build.gradle.kts
  src/main/java/cn/chahuyun/economy/HuYanEconomy.java
  src/main/java/cn/chahuyun/economy/event/MessageEventListener.java
  src/main/java/cn/chahuyun/economy/manager/RedPackManager.java
  src/main/java/cn/chahuyun/economy/manager/RobManager.java
  src/main/java/cn/chahuyun/economy/plugin/YiYanManager.java
  src/main/java/cn/chahuyun/economy/utils/ShareUtils.java
Labels: bug, enhancement

#13 [fix] 修复一些bug，新增富豪榜和抢劫权限
  README.md
  build.gradle.kts
  src/main/java/cn/chahuyun/economy/HuYanEconomy.java
  src/main/java/cn/chahuyun/economy/entity/rob/RobInfo.java
  src/main/java/cn/chahuyun/economy/event/MessageEventListener.java
  src/main/java/cn/chahuyun/economy/manager/BankManager.java
  src/main/java/cn/chahuyun/economy/manager/LotteryManager.java
  src/main/java/cn/chahuyun/economy/manager/RobManager.java
  src/main/java/cn/chahuyun/economy/manager/UserManager.java
  src/main/kotlin/cn/chahuyun/economy/config/EconomyConfig.kt
Labels: bug, enhancement

#14 [fix] 修复一些小问题
  build.gradle.kts
  src/main/java/cn/chahuyun/economy/HuYanEconomy.java
  src/main/java/cn/chahuyun/economy/manager/BankManager.java
  src/main/java/cn/chahuyun/economy/manager/GamesManager.java
  src/main/java/cn/chahuyun/economy/manager/RobManager.java
Labels: bug

#15 [fix] 修复一些问题，添加修复版本迭代问题的方法
  README.md
  build.gradle.kts
  src/main/java/cn/chahuyun/economy/HuYanEconomy.java
  src/main/java/cn/chahuyun/economy/entity/fish/FishInfo.java
  src/main/java/cn/chahuyun/economy/entity/fish/FishPond.java
  src/main/java/cn/chahuyun/economy/entity/fish/FishRanking.java
  src/main/java/cn/chahuyun/economy/manager/GamesManager.java
  src/main/java/cn/chahuyun/economy/manager/RobManager.java
  src/main/kotlin/cn/chahuyun/economy/command/EconomyCommand.kt
  src/main/kotlin/cn/chahuyun/economy/repair/Repair.kt
Labels: bug, documentation, enhancement
